on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  run_if_label_matches:
    if: contains(toJson(github.event.pull_request.labels.*.name), 'ready to merge') && (contains(toJson(github.event.pull_request.labels.*.name), 'minor') || contains(toJson(github.event.pull_request.labels.*.name), 'major') || contains(toJson(github.event.pull_request.labels.*.name), 'patch')) 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0      
      - name: Check for label and update version
        run: |
          LABEL_NAME=$(jq --raw-output '.label.name' "$GITHUB_EVENT_PATH")
          if [[ "$LABEL_NAME" == "major" || "$LABEL_NAME" == "minor" || "$LABEL_NAME" == "patch" ]]; then
            echo "label=$LABEL_NAME" >> $GITHUB_ENV
          fi 
      - name: Get current version and update
        run: |
          current_version=$(git describe --abbrev=0 --tags)
          a=(${current_version//./ })
          if [[ $label = "major" ]]; then
              ((a[0]++))
          elif [[ $label = "minor" ]]; then
              ((a[1]++))
          elif [[ $label = "patch" ]]; then
              ((a[2]++))
          fi
          new_version="${a[0]}.${a[1]}.${a[2]}"

          PY_INIT_FILE_PATH="utils/__init__.py"
          sed -i "s/__version__ = .*/__version__ = \"${new_version}\"/g" $PY_INIT_FILE_PATH

      - name: Commit and push if it has changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update version"
          git push
