on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
          echo INITIAL_PR_MESSAGE: $INITIAL_PR_MESSAGE
          echo ISSUE_COMMENT: $ISSUE_COMMENT
          # remove prefix up to and including __version__ = " and last quote
          VERSION=${ISSUE_COMMENT#__version__ = \"}; VERSION=${VERSION%\"}
          echo $VERSION


        env:
          NUMBER: ${{ github.event.issue.number }}
          INITIAL_PR_MESSAGE: ${{ github.event.issue.body }}
          ISSUE_COMMENT: ${{ github.event.comment.body }}


          
