on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  if_merged:
    if: ${{ github.event.labeled.name == 'ready to merge'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0      
      - name: Check for label and update version
        run: |
          LABEL_NAME=$(jq --raw-output '.label.name' "$GITHUB_EVENT_PATH")
          if [[ "$LABEL_NAME" == "major" || "$LABEL_NAME" == "minor" || "$LABEL_NAME" == "patch" ]]; then
            echo "$LABEL_NAME" > label.txt
          fi

      - name: Commit and push if it has changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update version"
          git push
