on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ISSUE_COMMENT: $ISSUE_COMMENT
          if [[ $ISSUE_COMMENT =~ ^__version__[[:space:]]*=[[:space:]]*\"([0-9]+\.[0-9]+\.[0-9]+)\"$ ]]; then
              # remove prefix up to and including __version__ = " and last quote
              PR_VERSION=${ISSUE_COMMENT#__version__ = \"}
              PR_VERSION=${PR_VERSION%\"}
              # Replace the old version with the new version in the python file
              sed -i "s/__version__ = \".*\"/__version__ = \"$PR_VERSION\"/g" $VERSION_FILE
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "chore: bump version"
              git push
          else
              VERSION=$(grep "__version__" $VERSION_FILE | awk -F= '{print $2}' | tr -d ' "' | tr -d "'")
              echo "$VERSION"
          fi
    
        env:
          NUMBER: ${{ github.event.issue.number }}
          INITIAL_PR_MESSAGE: ${{ github.event.issue.body }}
          ISSUE_COMMENT: ${{ github.event.comment.body }}
          VERSION_FILE: "utils/__init__.py"
