on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
          echo INITIAL_PR_MESSAGE: $INITIAL_PR_MESSAGE
          echo ISSUE_COMMENT: $ISSUE_COMMENT
          $(grep "__version__" $ISSUE_COMMENT | awk -F= '{print $2}' | tr -d ' "' | tr -d "'" | echo)
        env:
          NUMBER: ${{ github.event.issue.number }}
          INITIAL_PR_MESSAGE: ${{ github.event.issue.body }}
          ISSUE_COMMENT: ${{ github.event.comment.body }}
          VERSION: grep "__version__" $ISSUE_COMMENT | awk -F= '{print $2}' | tr -d ' "' | tr -d "'"
